![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [9]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [10]:
np.array([0] * 10)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [12]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [14]:
np.ones([2,2], dtype=int) #np. Command deprecated I'm going to use "int" instead of "np.int" for the remaining exercises.


array([[1, 1],
       [1, 1]])

In [15]:
np.ones([2,2], dtype=np.int)

C:\Users\LesT3\AppData\Local\Temp\ipykernel_21244\2225746612.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [16]:
np.ones([3,2], dtype=float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.ones([3,2], dtype=np.float)

C:\Users\LesT3\AppData\Local\Temp\ipykernel_21244\2134205708.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([3,2], dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [18]:
x = np.arange(4, dtype =int)

np.ones_like(x)


array([1, 1, 1, 1])

In [19]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

C:\Users\LesT3\AppData\Local\Temp\ipykernel_21244\2717597073.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.arange(4, dtype=np.int)


array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [20]:
x = np.array([[1,2,3],[4,5,6]], dtype=int)

np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [21]:
np.ones([4,4], dtype = int) * 5




array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
np.ones([4,4], dtype=np.int) * 5

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [22]:
x = np.array([[2,3], [6,2]], dtype =int)

np.ones_like(x) *7


array([[7, 7],
       [7, 7]])

In [38]:
X = np.array([[2,3], [6,2]], dtype=int)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [23]:
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#np.eye(3)
np.identity(3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [24]:
np.random.randint(10,size=3)


array([7, 2, 9])

In [ ]:
np.random.randint(10, size=3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [25]:
np.random.random((3,3,3))



array([[[0.23277006, 0.02961522, 0.24323443],
        [0.31210443, 0.41064867, 0.80680023],
        [0.16037069, 0.4611202 , 0.84397277]],

       [[0.16366552, 0.31021953, 0.21042692],
        [0.47120269, 0.86490288, 0.50523466],
        [0.64060666, 0.63742792, 0.8182053 ]],

       [[0.61116491, 0.06712388, 0.09194941],
        [0.74100007, 0.87114193, 0.11361619],
        [0.17685766, 0.51959712, 0.88856558]]])

In [25]:
np.random.randn(3,3,3)

array([[[-0.75262143, -0.7259127 , -0.12076796],
        [-0.65766241, -0.10662036,  0.97117796],
        [ 1.56040855, -0.03522264,  0.92372715]],

       [[-0.73173711, -0.72828723, -1.71892313],
        [ 1.68490185, -1.53332017,  1.27501396],
        [ 0.23510235,  0.67966337,  0.91525303]],

       [[ 1.19933581, -0.42171222,  1.24393394],
        [-0.13450263, -0.34840799, -1.34825298],
        [ 0.79673712, -0.66095229,  0.59258037]]])

In [ ]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [27]:
x = [3,6,9]
print(x, type(x))


[3, 6, 9] <class 'list'>


In [28]:
y = np.array(x)
print(y, type(y))

[3 6 9] <class 'numpy.ndarray'>


In [ ]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [46]:
x = np.array([5,2,3], dtype= int)
print(x, id(x))

[5 2 3] 2101025126320


In [47]:
y = np.copy(x)
print(y, id(y))

[5 2 3] 2101025127856


In [ ]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [30]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 11)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [34]:
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [35]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.arange(1, 11, 2)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [36]:
np.arange(1,11)[::-1]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [37]:
np.arange(1,11)[::1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###### np.arange(1, 11)[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [48]:
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.arange(9).reshape(3,3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [51]:
z = np.zeros((10,10))

print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [ ]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [52]:
x = np.array(['Z', 'Y', 'X', 'W', 'V', 'U'])

x[0]

'Z'

In [ ]:
X = np.array(['A','B','C','D','E'])

X[0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [53]:
x = np.array(['Z', 'Y', 'X', 'W', 'V', 'U'])

x[-1]

'U'

In [54]:
x = np.array(['Z', 'Y', 'X', 'W', 'V', 'U'])

x[len(x)-1]

'U'

In [55]:
print(len(x))

6


In [ ]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [56]:
x = np.array(['Z', 'Y', 'X', 'W', 'V', 'U'])

x[0:3]

array(['Z', 'Y', 'X'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [ ]:
# your code goes here


In [ ]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [58]:
x = np.array(['Z', 'Y', 'X', 'W', 'V', 'U'])

x[::-1]

array(['U', 'V', 'W', 'X', 'Y', 'Z'], dtype='<U1')

In [59]:
x = np.array(['Z', 'Y', 'X', 'W', 'V', 'U'])

x[::]

array(['Z', 'Y', 'X', 'W', 'V', 'U'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [60]:
x = np.array(['Z', 'Y', 'X', 'W', 'V', 'U'])

x[::2]


array(['Z', 'X', 'V'], dtype='<U1')

In [63]:
x = np.array(['Z', 'Y', 'X', 'W', 'V', 'U'])

x[[0,2,4]]


array(['Z', 'X', 'V'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [72]:
x = np.random.randint(100, size=(10,10))
print(x, x[0])        



[[14 25 50 57 27 74 46 78 82  4]
 [32 23 80 18 44  8 80 41 48 31]
 [94 37  1 63 83 51 25 98 41 90]
 [ 3 43 70 49 10 80 49 31 21 73]
 [65 12 17 21  7 28  9 21 50 44]
 [44 59 95 44 97 77  0 20 88 46]
 [91 97 67 59 86 30 75 97 99 84]
 [53 19 14 34 92 38 78 87 67 54]
 [ 9 16 94 56 69 80 39 86 88 25]
 [24 60 60  1 26 95  1 67 69 96]] [14 25 50 57 27 74 46 78 82  4]


In [74]:
print(x, x[-1]) 

[[14 25 50 57 27 74 46 78 82  4]
 [32 23 80 18 44  8 80 41 48 31]
 [94 37  1 63 83 51 25 98 41 90]
 [ 3 43 70 49 10 80 49 31 21 73]
 [65 12 17 21  7 28  9 21 50 44]
 [44 59 95 44 97 77  0 20 88 46]
 [91 97 67 59 86 30 75 97 99 84]
 [53 19 14 34 92 38 78 87 67 54]
 [ 9 16 94 56 69 80 39 86 88 25]
 [24 60 60  1 26 95  1 67 69 96]] [24 60 60  1 26 95  1 67 69 96]


In [ ]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [53]:
x = np.array([
    [2,5,7,8],
    [7,2,1,0],
    [8,12,3,5],
    [7,4,5,7]
        
])

x[-1]

array([7, 4, 5, 7])

In [52]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [55]:
x = np.array([
    [2,5,7,8],
    [7,2,1,0],
    [8,12,3,5],
    [7,4,5,7]
        
])

x[0,0]

2

In [56]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [57]:
x = np.array([
    [2,5,7,8],
    [7,2,1,0],
    [8,12,3,5],
    [7,4,5,7]
        
])

x[3,3]

7

In [58]:
x = np.array([
    [2,5,7,8],
    [7,2,1,0],
    [8,12,3,5],
    [7,4,5,7]
        
])

x[-1,-1]

7

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [72]:
x = np.array([
    [2,5,7,8],
    [7,2,1,0],
    [8,12,3,5],
    [7,4,5,7]
        
])

x[1:-1, 1:-1]


array([[ 2,  1],
       [12,  3]])

In [78]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [80]:
x = np.array([
    [2,5,7,8],
    [7,2,1,0],
    [8,12,3,5],
    [7,4,5,7]
        
])

x[:2, :2]

array([[2, 5],
       [7, 2]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [83]:
x = np.array([
    [2,5,7,8],
    [7,2,1,0],
    [8,12,3,5],
    [7,4,5,7]
        
])

x[2:, 2:]

array([[3, 5],
       [5, 7]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [95]:
x =[-4,5,9,6,20]

np.array(x,float)


AttributeError: 'list' object has no attribute 'type'

In [87]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

C:\Users\LesT3\AppData\Local\Temp\ipykernel_21244\4247539020.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(X, np.float)


array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [96]:
x = [9,6, 15,-3,0,2,4]

x[::-1]


[4, 2, 0, -3, 15, 6, 9]

In [ ]:
X = [-5, -3, 0, 10, 40]

X[::-1]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [97]:
x = [2,5,-7,9,10]

x.sort()
x


[-7, 2, 5, 9, 10]

In [ ]:
X = [0, 10, -5, 40, -3]

X.sort()
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [102]:
x = np.ones(10)
x[4] = 2
x


array([1., 1., 1., 1., 2., 1., 1., 1., 1., 1.])

In [103]:
x = np.zeros(10)
x[6] = 1
x

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [104]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
X = np.zeros(10)

X[4] = 1
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [105]:
x = np.array([5,2,5,70,80])
x[4] = 90
x

array([ 5,  2,  5, 70, 90])

In [ ]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [106]:
x = np.array([
    [5,8,23,1],
    [4,45,8,32],
    [6,2,77,21],
    [9,2,4,6]
    
])


x[-1] = np.array([1,1,1,1])
x

array([[ 5,  8, 23,  1],
       [ 4, 45,  8, 32],
       [ 6,  2, 77, 21],
       [ 1,  1,  1,  1]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [109]:
x = np.array([
    [5,8,23,1],
    [4,45,8,32],
    [6,2,77,21],
    [9,2,4,6]
])

x[-1,-1] = 0

x

array([[ 5,  8, 23,  1],
       [ 4, 45,  8, 32],
       [ 6,  2, 77, 21],
       [ 9,  2,  4,  0]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [110]:
x = np.array([
    [5,8,23,1],
    [4,45,8,32],
    [6,2,77,21],
    [9,2,4,6]
])

x + 5


array([[10, 13, 28,  6],
       [ 9, 50, 13, 37],
       [11,  7, 82, 26],
       [14,  7,  9, 11]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [49]:
x = np.array([-1,5,-4,43,6,0,43,-12,-4])

mask = x > 1
mask


array([False,  True, False,  True,  True, False,  True, False, False])

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [48]:
x = np.array([-1,5,-4,43,6,0,43,-12,-4])

mask = x <= -1
x[mask]


array([ -1,  -4, -12,  -4])

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [45]:
x = np.array([-1,5,-4,43,6,0,43,-12,-4])

mask = x > 1
x[mask]


array([ 5, 43,  6, 43])

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [44]:
x = np.array([-1,5,-4,43,6,0,43,-12,-4])

mask = x > x.mean()
x[mask]


array([43, 43])

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [43]:
x = np.array([-1,5,-4,43,6,0,43,-12,-4])

mask = (x== 43) | (x == -4)
x[mask]


array([-4, 43, 43, -4])

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [41]:
x = np.array([4,0,-8,92,0,-55,-1,0,56,7])

x.all()


False

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [40]:
x = np.array([4,0,-8,92,0,-55,-1,0,56,7])

x.any()

True

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [34]:
x = np.array([2,3,65,72,93,78,13,0,23,111])

x.sum()

460

In [ ]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [32]:
x = np.array([2,3,65,72,93,78,13,0,23,111])

x.mean()

46.0

In [ ]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [30]:
x = np.array([
 [4,7,5,78],   
 [9,345,23,13],  
 [56,24,69,860],
[24,42,0,187]
    
])

x.mean(axis=0)

array([ 23.25, 104.5 ,  24.25, 284.5 ])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [29]:
x = np.array([
 [4,7,5,78],   
 [9,345,23,13],  
 [56,24,69,860],
[24,42,0,187]
    
])

x.mean(axis=1)

array([ 23.5 ,  97.5 , 252.25,  63.25])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [27]:
x= np.array([4,556,1322,41,43,6,1,6,9,3,0])

x.max()


1322

In [ ]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)